### ISSUE TITLE
API not working

### ISSUE THREAD

**Issue by WobbyChip** [naziks/aniapp#1] opened 2022-04-28 11:16 UTC
![image](https://user-images.githubusercontent.com/66483092/165740448-f9b8b5cd-b072-46c9-9475-dbfc21a48af7.png)

**Comment by naziks** [comment] 2022-06-08 01:50
It caused by moving to another server. Now there is a better version of anime player. But still under development. If you are interested contact me for more info. ^_^

**Closed** 2022-06-08 22:42 UTC
